Init project v 0.1
676767ap/otus-go-hw pull request #14
Opened 2023-05-22 16:16 UTC by 676767ap

2023-05-23 06:33 UTC, dshemin requested changes

2023-05-23 06:33 UTC, dshemin commented on project/Makefile
> +run: build
Критично:

> Развертывание микросервиса должно осуществляться командой make run (внутри docker compose up) в директории с проектом.

2023-05-23 06:33 UTC, dshemin commented on project/cmd/main.go
> +// @title        nationaleducation.ru
Важно:

Кажется название и описание не совпадает с тем, что мы делаем.

2023-05-23 06:33 UTC, dshemin commented on project/docker-compose.test.yaml
> +    environment:
Важно:

Зачем все эти переменные окружения в контейнере с постгрюй? Кажется они тут не нужны.

2023-05-23 06:33 UTC, dshemin commented on project/docker-compose.test.yaml
> +      - postgres
Важно:

В данный момент сервис зависит просто от того, что контейнеры запущены, а не живы. Надо указать что сервис должен быть "жив"

https://docs.docker.com/compose/startup-order/

2023-05-23 06:33 UTC, dshemin commented on project/docker-compose.yaml
> +      - postgres
Важно:

Тут тоже https://docs.docker.com/compose/startup-order/

2023-05-23 06:33 UTC, dshemin commented on project/docker-compose.yaml
> +      PROJECT_DEV_MODE: false
Важно:

В контейнере постгрес есть зависимость от этой переменной окружения?

2023-05-23 06:33 UTC, dshemin commented on project/docker/banners-rotator.dockerfile
> +FROM alpine:3.9
Важно:

Можно `FROM scratch` чтобы сделать образ меньше.

2023-05-23 06:33 UTC, dshemin commented on project/go.mod
> +module github.com/676767ap/project
Критично:

Неверный путь модуля. Должен совпадать с названием репозитори т.е. должен быть. https://github.com/676767ap/otus-go-hw.

Для простого переименования можно использовать вот эту утилиту: https://pkg.go.dev/golang.org/x/tools/cmd/gorename
Если пользуетесь Goland, то: https://www.jetbrains.com/go/guide/tips/rename-go-module-name/

2023-05-23 06:33 UTC, dshemin commented on project/infrastructure/database/database.go
> +	dsn := "host=" + cfg.PostgreSQL.Host + " user=" + cfg.PostgreSQL.User + " password=" + cfg.PostgreSQL.Password + " dbname=" + cfg.PostgreSQL.Database +
Важно:

Лучше собирать такие строки через fmt.Sprintf

2023-05-23 06:33 UTC, dshemin commented on project/infrastructure/database/database.go
> +	migrate(db)
Важно:

Не самое лучшее решение мигрировать базу прям в сервисе. Для этого должна быть отдельная команда. Представьте мы деплоим в k8s несколько инстансов нашего приложения и они все, практически одновременно, пойдут мигрировать базу.

2023-05-23 06:33 UTC, dshemin commented on project/infrastructure/database/database.go
> +		log.Fatal("DB Shutdown:", err)
Важно:

Лучше вернуть ошибку чем обрушить всё приложение.

2023-05-23 06:33 UTC, dshemin commented on project/infrastructure/database/database.go
> +	sqlDB.Close()
Важно:

Данный метод возвращает ошибку? Если да - то её надо вернуть.

2023-05-23 06:33 UTC, dshemin commented on project/infrastructure/database/database.go
> +		log.Fatal("DB AutoMigrate:", err)
Важно:

Лучше вернуть ошибку.

2023-05-23 06:33 UTC, dshemin commented on project/infrastructure/database/database.go
> +		log.Fatal("DB Open:", err)
Важно:

Надо возвращать ошибку.

2023-05-23 06:33 UTC, dshemin commented on project/internal/app/app.go
> +	api.POST("/add-banner-to-slot/{banner_id}/{slot_id}", a.addBannerToSlot)
Важно:

Это не REST API, это RPC (Remote Procedure Call): https://blog.skillfactory.ru/glossary/rest-api/

2023-05-23 06:33 UTC, dshemin commented on project/internal/app/banner.go
> +	bannerId, _ := strconv.ParseInt(ctx.Param("banner_id"), 10, 32)
Важно:

Не надо игнорировать ошибку! Иначе тут будет bannerId будет 0 и как нам потом различить ситуацию когда пользователь отправил 0 и когда пользователь отправил "foo"?

Пожалуйста самостоятельно найдите все подобные места и поправьте.

2023-05-23 06:33 UTC, dshemin commented on project/internal/repository/interface.go
> +	AddBannerToSlot(bannerId int32, slotId int32) error
Важно:

Почему именно int32? Не протекает ли абстракция?

2023-05-23 06:33 UTC, dshemin commented on project/internal/entity/stats.go
> +type Stat struct {
Важно:

Внимательно посмотрите на задание https://github.com/OtusGolang/final_project/blob/master/02-banners-rotation.md#%D0%B2%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D1%81%D1%82%D0%B8%D0%BA%D0%B8

Нам не надо сохранять статистику в базу, надо её просто отправить в очередь.

2023-05-23 06:33 UTC, dshemin commented on project/internal/repository/banners.go
> +	var banner = &entity.Banner{}
Важно:

Лучше `banner := &entity.Banner{}`

2023-05-23 06:33 UTC, dshemin commented on project/internal/repository/banners.go
> +	if err != nil {
Важно:

Если не оборачивается ошибка, то проще вернуть err и всё.

2023-05-23 06:33 UTC, dshemin commented on project/internal/repository/banners.go
> +	err = g.CreateStat(&stat)
Важно:

Как уже писал выше, статистика должна отправляться в очередь а не в базу.

2023-05-23 06:33 UTC, dshemin commented on project/internal/repository/banners.go
> +	choosenBannerId := services.MaxUCB1(bannersForCalc)
Совет:

В итоге мы имеем следущее:
1. Обработчик (инфраструктура)
2. Репозиторий (инфраструктура)
3. Сервис (бизнес логика)

А должно быть немного иначе: сервис должен вызывать репозиторий. Сейчас нам логику рассчёта надо будет добавлять в каждую имплементацию репозитория, а она не зависит от того с какой БД мы работаем!

Это совет на будущее, можно не исправлять.

2023-05-23 06:33 UTC, dshemin commented on project/internal/services/rabbitMQ.go
> +	Consume(ctx context.Context, queueName, consumerName string) (<-chan amqp.Delivery, error)
Критично:

Мы должны отправлять, а не получать.

> Микросервис должен отправлять события кликов и показов в очередь (например kafka) для дальнейшей обработки в аналитических системах.

2023-05-23 06:33 UTC, dshemin commented on project/internal/usecase/usecase.go
> +type Repos struct {
Важно:

Для чего нам эта абстракция если она только проксирует вызовы в репозиотрий?

2023-05-23 09:00 UTC, 676767ap commented on project/internal/services/rabbitMQ.go
> +	Consume(ctx context.Context, queueName, consumerName string) (<-chan amqp.Delivery, error)
Consume я убрал, а отправка там вроде корректная в sendEvent, который и используется для отправки, но используется из контроллера

2023-05-23 09:01 UTC, 676767ap commented on project/internal/repository/banners.go
> +	choosenBannerId := services.MaxUCB1(bannersForCalc)
Вот не подумал об этом, да.

2023-05-23 09:02 UTC, 676767ap commented on project/internal/repository/banners.go
> +	err = g.CreateStat(&stat)
А тут скорее косяк в именовании, эта сущность в БД по-сути конечно и представляет статистику, но на деле используется для подсчёта в формуле, отправка этой же собственно сущности в кролик идёт из контроллера

2023-05-23 09:02 UTC, 676767ap commented on project/cmd/main.go
> +// @title        nationaleducation.ru
))) Ну да, я брал в качестве скелета свой же рабочий проект

2023-05-23 09:04 UTC, 676767ap commented on project/internal/usecase/usecase.go
> +type Repos struct {
Это тоже артефакт от проекта остался, вообще это задел на будущее, чтобы можно было использовать не только Горм, но и тот же Рэдис например, иметь разные короче репозитории

2023-05-24 07:08 UTC, dshemin approved these changes

2023-05-24 07:08 UTC, dshemin commented on project/internal/repository/banners.go
> +	err = g.CreateStat(&stat)
Я о том, что сохранение в БД делается, а этого быть не должно. Основной смысл это статистики - отправлять данный во внешние системы. Само приложение их хранить не должно.

2023-05-24 08:02 UTC, 676767ap commented on project/internal/repository/banners.go
> +	err = g.CreateStat(&stat)
Я вас понял, но для самой работы данные по кликам и показам нужны тем не менее, предлагается в кэше их хранить?

2023-05-24 20:57 UTC, merged